# Generated by Django 4.0.2 on 2022-03-07 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_period', models.IntegerField()),
                ('last_run_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CitiesWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('temperature_celcius', models.FloatField()),
                ('humidity', models.IntegerField(default=0)),
                ('weather', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities.city')),
            ],
        ),
    ]
